config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  root 'static_pages#home'
  get '/about', to:'static_pages#about'
  get '/signup', to: 'users#new'
  post '/signup',to: 'users#create'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  resources :users
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :name, presence: true, length: {maximum: 50}
    validates :email, presence: true,  length: { maximum: 250 },
        format: {with: VALID_EMAIL_REGEX },  
        uniqueness: {case_sensitive: false}
        
    has_secure_password
    validates :password,presence: true, length: {minimum: 6}
    
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
                BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
    def about
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new #method register user new
    @user = User.new
  end
  
  def create #moethod post for new user ตรวจความถูกตอนกรอกฟอร์ม
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Spec-pc"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
    
  end
  
  
  private
  def user_params
    params.require(:user).permit(:name,:email,
    :password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_tile(page_title = '')
        base_title = "Spec-PC Application"
        if page_title.empty?
            base_title
        else
            page_title + "||" + base_title
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user
        if session[:user_id]
            @current_user = @current_user || User.find_by(id: session[:user_id])
        end
    end
    
    def logged_in?
        !current_user.nil?
    end
    
    def log_out
        session.delete(:user_id)
        @current_user =nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user,option = {size: 80})
        
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = option[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_footer.html.erb
<footer>
    <a name="footer"></a>
    <div class="footer_text">
        <div style="text-align: center;">
            <%= image_tag( "Admin2.png" ,:style => 'float:left;margin-left: 10px;margin-bottom: 20px;') %>
            <h3>Hi, <a href="#">I'm ADMIN</a></h3>

            <p><b style="font-size: 15px"> จัดสเปกคอมคิดถึงเรา
                    เรามีมือโปรในการเลือกชิ้นส่วนอุปกรณ์ที่สามารถดึงประสิทธิภาพของอุปกรณ์แต่ล่ะชิ้นออกมาได้อย่างลงตัว<br>ในราคาที่คุณต้องว้าว
                    ทุกงานบริการของเรามั่นใจได้ว่าคุณจะใช้งานคอมพิวเตอร์ได้อย่างเต็มความสามารถสมกับที่วางใจใช้บริการของเรา</br>
                </b></p>
        </div>
    </div>
    <br>
    <br>
    <br>
    <div class="footer_copyright">
        &copy; 2018 <a href="#">เสปกคอมพิวเตอร์</a> - CN340 <br>
    </div>
</footer>

app/views/layouts/_header.html.erb
 <header class="site-header">
        
        <%= image_tag("egg3.gif", height: '110', width: '110',:style =>'float:right;' ) %>
        <h1 class="topic "style="color: slategray;text-shadow: -1px -1px white, 1px 1px #333;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ผู้ช่วยจัดสเปคคอม ที่ดีที่สุดของคุณ </h1>
        <nav>
            <ul>
               
                <li ><a id="welcome" > <i class="fa fa-id-card" aria-hidden="true"></i> ยินดีต้อนรับ</li>
                <li><%= link_to raw('<span class="fa fa-home" aria-hidden="true"></span> Home'), root_path%></li>
                <li><%= link_to raw('<span class="fa fa-angellist" aria-hidden="true"></span> About'), about_path %></li>
                
                <% if logged_in? %>
                  <li><%= link_to "Users", '#' %></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Settings", '#' %></li>
                      <li class="divider"></li>
                      <li>
                          <%= link_to raw('<span class="fa fa-sign-out" aria-hidden="true"></span> Sign out'), signout_path,:method => :delete%>
                      </li>
                      
                    </ul>
                  </li>
                <% else %>
                  <li><%= link_to raw('<span class="fa fa-sign-in" aria-hidden="true"></span> Sign in'),signin_path %></li>
                  <li><%= link_to raw('<span class="fa fa-key" aria-hidden="true"></span> Sign up'), signup_path %></li>
                <% end %>
    
            </ul>
        </nav>
        

    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_tile(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Inconsolata|Kalam" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Taviraj:300" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Athiti" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!--<link href="assets/stylesheet/static_pages.scss" rel="stylesheet" >-->
  <style>
     .contain{
       
        margin: auto;
        padding: 20px;
        width: 900px;
        /*height: 1998px;*/
        border:20px;
        border-color:; #ffaa77;
        background-color:cornsilk;
        font-family: "Short Stack";
       
        
    }
    .bg-faded {
  background-color: palegoldenrod;
 
    }
    .card {
  position: relative;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-direction: column;
      flex-direction: column;
  min-width: 0;
  word-wrap: break-word;
  /*background-color: gainsboro;*/ 
  background-clip: border-box;
  border: 1px solid rgba(0, 0, 0, 0.125);
  border-radius: 0.25rem;
  padding:20px;
}
/*.card-img-overlay {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  padding: 1.25rem;
}*/
.bg-overlay {
  background-color: rgba(0, 0, 0, 0.7);
}
.tablebox{
    padding:20px;
}

  </style>
</head>
  <body>
     <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <div class = "container">
      
     
  
      <%= render 'layouts/header' %>
      
      <%= yield %>
      
      <%= render 'layouts/footer' %>
      
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<link href="https://fonts.googleapis.com/css?family=Short+Stack" rel="stylesheet">
<link href="assets/stylesheet/welcome.scss" rel="stylesheet" >
<style>
    .contain{
       
        margin: auto;
        padding: 20px;
        width: 900px;
        /*height: 1998px;*/
        border:20px;
        border-color:; #ffaa77;
        background-color:cornsilk;
        font-family: "Short Stack";
       
        
    }
    .bg-faded {
      background-color: palegoldenrod;
    }
    .card {
      position: relative;
      display: -ms-flexbox;
      display: flex;
      -ms-flex-direction: column;
      flex-direction: column;
      min-width: 0;
      word-wrap: break-word;
      /*background-color: gainsboro;*/ 
      background-clip: border-box;
      border: 1px solid rgba(0, 0, 0, 0.125);
      border-radius: 0.25rem;
      padding:20px;
    }
/*.card-img-overlay {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  padding: 1.25rem;
}*/
.bg-overlay {
  background-color: rgba(0, 0, 0, 0.7);
}
.tablebox{
    padding:20px;
}

</style>
<main class ="main-area">
    <div class = "card card-inverse">
          
         <h1 style="color:black"><b>ABOUT</b></h1>
        <table>
            <tr><ul>
                <tr><h3 style="color:black" ><b>MEMBER</b></h3></tr>
                <tr><td style="color:black;font-size: 120%"><li><b>Jirayu</b></li><td style="color:black;font-size: 120%"><b>&nbsp Srisuk</b></td><td style="color:black;font-size: 120%"><b>&nbsp 5710520197</b></td></tr>
                <tr><td style="color:black;font-size: 120%"><li><b>Natchawi</b></li></td><td style="color:black;font-size: 120%"><b>&nbsp Muangpa</b></td><td style="color:black;font-size: 120%"><b>&nbsp 5710520213</b></td></tr>
                <tr><td style="color:black;font-size: 120%"><li><b>Nonthicha</b></li></td><td style="color:black;font-size: 120%"><b>&nbsp Suwansilsak</b></td><td style="color:black;font-size: 120%"><b>&nbsp 5810613439</b></td></tr>
                <tr><td style="color:black;font-size: 120%"><li><b>Varaporn</b></li></td><td style="color:black;font-size: 120%"><b>&nbsp Ellermann</b></td><td style="color:black;font-size: 120%"><b>&nbsp 5910613354</b></td></tr>
            </ul></tr>
        </table>
        
        <article class = "Requirements" ><h3 style="color:black"><b>Requirement</b></h3>
        <p >
           <ul><li style="color:black;font-size: 120%"><b>1. มีระบบ Register สามารถสมัครสมาชิกเพื่อทำการ Login เพื่อมีสิทธิเข้าใช้งาน Web Application ได้​
                <br>
                2. มีระบบ Login เพื่อมีสิทธิเข้าใช้งาน Web Application ได้​
                <br>
                3. มีที่เลือกอุปกรณ์ตามช่วงราคาที่ต้องการได้​
                <br>
                4. มีการเพิ่มข้อมูลต่างๆ เช่น สถานที่ซื้อ รุ่นของสินค้า ยี่ห้อของสินค้า และราคาของสินค้า​
                <br>
                5. สามารถอ่าน Post ได้​
                <br>
                6. สามารถแก้ไข Post ที่ตนเอง Post ได้​
                <br>
                7. สามารถลบ Post ที่ตนเอง Post ได้​
                <br>
                8. Admin สามารถแก้ไข ลบ และอัพเดต Post ของทุกคนได้ ​
                <br>
                9. มีระบบ Logout เมื่อต้องการออกจากระบบ</b></li></ul>
        </p>
        </article>
        
        
        <article class = "Project proposal"><h3 style="color:black"><b>Project proposal</b></h3>
        <p>
            <ul style="color:black"><li><a href = "https://drive.google.com/file/d/1lNgTvK0JaW4ZvCnOb46-JfBmPuK0RDTd/view?usp=sharing" style="color:black;font-size: 120%" target="_blank"><b>Project proposal</b></a></li></ul>
        </p>
        </article>
        <article class = "ER-diagram"><h3 style="color:black"><b>ER-diagram</b></h3>
        <p>
            
            <%= image_tag("er.jpg", alt: "ER-diagram")%>
        </p>
        </article>
        
        <article class = "Tracker"><h3 style="color:black"><b>Tracker</b></h3>
        <p>
            <ul style="color:black"><li><a href = "https://www.pivotaltracker.com/n/projects/2209354" style="color:black;font-size: 120%" target="_blank"><b>Pivotal Tracker</b></a></li></ul>
        </p>
        </article>
        
        <article class = "Bitbucket"><h3 style="color:black"><b>Bitbucket</b></h3>
        <p>
            <ul style="color:black"><li><a href = "https://bitbucket.org/softend/soften-myapp" style="color:black;font-size: 120%" target="_blank"><b>Bitbucket</b></a></li></ul>
        </p>
        </article>
        
        <article class = "YouTube"><h3 style="color:black"><b>YouTube</b></h3>
        <p>
            <ul style="color:black"><li><a href = "https://youtu.be/aux2W-ggVag" style="color:black;font-size: 120%" target="_blank"><b>Presentation</b></a></li></ul>
            
        </p>
        </article>
        
        
        <article class = "UserStory"><h3 style="color:black"><b>UserStory</b></h3>
        <b>Iteration 1</b><br>
        <%= image_tag("01.jpg", alt: "feature1",width:'480',height:'240' )%>
        <%= image_tag("02.jpg", alt: "feature2",width:'480',height:'240' )%>
        <%= image_tag("03.jpg", alt: "feature3",width:'480',height:'240' )%><br>
        <b>Iteration 2</b><br>
        <%= image_tag("04.jpg", alt: "feature4" ,width:'480',height:'240' )%>
        <%= image_tag("05.jpg", alt: "feature5",width:'480',height:'240' )%>
        <%= image_tag("06.jpg", alt: "feature6",width:'480',height:'240' )%>
        <%= image_tag("08.jpg", alt: "feature8",width:'480',height:'240' )%>
        <%= image_tag("07.jpg", alt: "feature7",width:'480',height:'240' )%><br>
        <b>Iteration 3</b><br>
        <%= image_tag("09.jpg", alt: "feature9",width:'480',height:'240' )%>
        <br><br>
        </article>
        
           </div>
    </div>
</main>

app/views/static_pages/home.html.erb
<main class="main-area">
    
    <article style='color: red ;font-size:15px; font-weight: bold';>กรุณากรอกข้อมูลเป็นตัวเลขให้ถูกต้อง</article>
    <article class="test"><h3>ค้นหาราคาที่ต้องการ</h3></article>
    <label id="field">ราคาเริ่มต้น :</label><input  id="block_search" type="text" name="min_price" value=""/>
    <label id="field">ราคาสูงสุด :</label><input id="block_search"   type="text" name="max_price" value=""/>
    <a href="<?=base_url('Main/search_all') ;?> "style="text-align: right; color: darkblue">ค้นหาทั้งหมด</a>
    <input id="buttom_login" type="submit" name="submit" value="Search">

  

</main>

app/views/users/new.html.erb
<% provide(:title , 'Sing up') %>
<style>
input, textarea, select, .uneditable-input {
  border: 1px solid #bbb;
  width: 100%;
  margin-bottom: 15px;
  @include box_sizing;
}

input {
  height: auto !important;
}
 .contain{
       
        margin: auto;
        padding: 20px;
        width: 900px;
        /*height: 1998px;*/
        border:20px;
        border-color:; #ffaa77;
        background-color:cornsilk;
        font-family: "Short Stack";
       
        
    }
    .bg-faded {
  background-color: palegoldenrod;
 
    }
    .card {
  position: relative;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-direction: column;
      flex-direction: column;
  min-width: 0;
  word-wrap: break-word;
  /*background-color: gainsboro;*/ 
  background-clip: border-box;
  border: 1px solid rgba(0, 0, 0, 0.125);
  border-radius: 0.25rem;
  padding:20px;
}
/*.card-img-overlay {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  padding: 1.25rem;
}*/
.bg-overlay {
  background-color: rgba(0, 0, 0, 0.7);
}
.tablebox{
    padding:20px;
}

</style>


<main class ="main-area">
  
    <h1>Sign up</h1>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user,url: signup_path) do |f| %>
          <%= render 'shared/error_messages' %>
          <%= f.label :name %>
          <%= f.text_field :name ,:size => "2", class: 'form-control'%>
  
          <%= f.label :email %>
          <%= f.text_field :email,:size => "20", class: 'form-control' %>
  
          <%= f.label :password %>
          <%= f.password_field :password, :size => "2",class: 'form-control' %>
  
          <%= f.label :password_confirmation,"Confirmation" %>
          <%= f.password_field :password_confirmation, :size => "2",class: 'form-control' %>

  
          <%= f.submit "Sign up" %>
  
        <% end %>
      </div>
    </div>
  
</main>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<style>
    /* sidebar */

aside {
  section.user_info {
    margin-top: 20px;
  }
  section {
    padding: 10px 0;
    margin-top: 20px;
    &:first-child {
      border: 0;
      padding-top: 0;
    }
    span {
      display: block;
      margin-bottom: 3px;
      line-height: 1;
    }
    h1 {
      font-size: 1.4em;
      text-align: left;
      letter-spacing: -1px;
      margin-bottom: 3px;
      margin-top: 0px;
    }
  }
}

.gravatar {
  float: left;
  margin-right: 10px;
}

.gravatar_edit {
  margin-top: 15px;
}

</style>

<main class="main-area">
    <div class="row">
        <aside class="col-md-4">
            <section class="user_info">
                <h1>
                  <%= gravatar_for @user %>
                  <%= @user.name %>
                </h1>
            </section>
        </aside>
    </div>
    
    <%= @user.email %>,<%= @user.name %>
</main>